### ISSUE TITLE
Concept to replace models with component collections

### ISSUE THREAD

**Issue by raffomania** [Gamemaker-AG/secret-octo-dangerzone#23]
- how do we call the new models? "component collection" seems clunky to me
  - Let's call it a collection anyway
- how do we create and specify those collections?
  - We create a helper function for each model that automatically adds a list of components to a given entity
- do we need further integration with the love toys?
  - we don't know if this pattern will actually be that useful, so not yet.
- could we kind of merge this with the concept of identifiers?
  - No, identifiers are cool

**Comment by Nukesor** [comment]
Should be done
